### ISSUE TITLE
Too many values to unpack (expected 2) Error

### ISSUE THREAD

**Issue by 5eyegeo** [DJWOMS/oms_cms#84]
I'm facing error while trying to install this..
![Screenshot from 2019-09-11 22-15-26](https://user-images.githubusercontent.com/50432591/64716211-b02d4e00-d4e1-11e9-8253-217fe58540a4.png)

**Comment by saileshkush95** [comment]
Facing error after generating templates

**Comment by DJWOMS** [comment]
Hello, tell me how to reproduce the error?

**Comment by DJWOMS** [comment]
> I'm facing error while trying to install this..
> ![Screenshot from 2019-09-11 22-15-26](https://user-images.githubusercontent.com/50432591/64716211-b02d4e00-d4e1-11e9-8253-217fe58540a4.png)

Hello, tell me how to reproduce the error?

**Comment by DJWOMS** [comment]
Hello, thanks for finding and pointing out the error. The bug was fixed in the new version 0.5.2
